"""Opt-in real model test; emits only timing/status, never credentials or payloads.

Run from repo root: .venv/bin/python agents/weapon_smith/live_probe.py
Uses root .env API key. Local SDK ASGI REST transport (no socket/network registration).
This measures full authenticated REST handler + live model + TypeScript adapter roundtrip;
it does NOT measure a deployed network hop or ASI discovery.
"""
import asyncio
import base64
import json
import os
import secrets
import sys
import time
from pathlib import Path
import httpx
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[2] / '.env')
os.environ.setdefault('AGENT_SEED', secrets.token_hex(32))
os.environ.setdefault('AGENT_SHARED_SECRET', secrets.token_hex(32))
os.environ['AGENT_MAILBOX'] = 'false'

async def main():
    # Local probes must not publish or register their temporary identity.
    from unittest.mock import patch
    from uagents import Agent
    include = Agent.include
    with patch.object(Agent, "include", lambda self, proto, publish_manifest=False: include(self, proto, publish_manifest=False)):
        import agent
    if not os.getenv('ASI_ONE_API_KEY'):
        print('No ASI_ONE_API_KEY configured'); return
    # Existing fixture drawing generated by prompt-lab, if supplied; otherwise text-only.
    png = base64.b64encode(Path(sys.argv[1]).read_bytes()).decode() if len(sys.argv) > 1 else ''
    async with httpx.AsyncClient(transport=httpx.ASGITransport(app=agent.agent._server), base_url='http://local') as client:
        started = time.monotonic()
        res = await client.post('/spec', json={
            'token': os.environ['AGENT_SHARED_SECRET'], 'png_base64': png,
            'features_json': Path(sys.argv[2]).read_text() if len(sys.argv) > 2 else '{}', 'flavor': 'mythic', 'seed': 42,
        })
        data = res.json()
        print(json.dumps({'test': 'live-model/local-SDK-REST', 'duration_s': round(time.monotonic() - started, 3),
                          'http_status': res.status_code, 'status': data['error'] or 'success',
                          'valid_artifact': bool(data.get('weapon_json'))}))
    # Complete ACP conversation handler with a live text model; transport/sender are local.
    from types import SimpleNamespace
    from unittest.mock import AsyncMock
    from uagents_core.contrib.protocols.chat import ChatMessage, TextContent
    from uuid import uuid4
    from chat import handle_message
    class Store:
        def __init__(self): self.data = {}
        def get(self, key): return self.data.get(key)
        def set(self, key, value): self.data[key] = value
    ctx = SimpleNamespace(session=uuid4(), storage=Store(), send=AsyncMock(), logger=agent.agent._logger)
    started = time.monotonic()
    await handle_message(ctx, 'local-probe', ChatMessage(content=[TextContent(text='Create a frost spear with slow on-hit and blue runes')]))
    reply = ctx.send.await_args_list[-1].args[1]
    print(json.dumps({'test': 'live-text/local-ACP-handler', 'duration_s': round(time.monotonic() - started, 3),
                      'ack_and_reply': ctx.send.await_count == 2, 'valid_artifact': '```json' in reply.content[0].text}))

if __name__ == '__main__': asyncio.run(main())
