import type { Identity } from 'spacetimedb';
// Generated by `pnpm stdb:generate` — run it after every server schema change.
import { DbConnection } from '../module_bindings';
import { DEBUG, debug } from '../debug';

const URI = import.meta.env.VITE_STDB_URI ?? 'ws://localhost:3000';
const DB = import.meta.env.VITE_STDB_DB ?? 'doodle-arena';

export interface Connected {
  conn: DbConnection;
  identity: Identity;
}

/**
 * Connect with a per-role token so a laptop can be both /screen and /play in two tabs
 * during dev without sharing an identity. Tokens persist in localStorage → reconnecting
 * phones keep their player row + color.
 */
export function connect(role: 'screen' | 'play'): Promise<Connected> {
  const tokenKey = `doodle.token.${role}`;
  let saved: string | undefined;
  try { saved = localStorage.getItem(tokenKey) ?? undefined; } catch { /* private mode */ }

  return new Promise((resolve, reject) => {
    DbConnection.builder()
      .withUri(URI)
      .withDatabaseName(DB)
      .withToken(saved)
      .onConnect((conn, identity, token) => {
        try { localStorage.setItem(tokenKey, token); } catch { /* ignore */ }
        if (DEBUG) {
          const since = Date.now();
          debug.addProvider(() => [{ level: 'ok', text: `${role} · connected ${Math.round((Date.now() - since) / 1000)}s · ${URI}/${DB} · me ${identity.toHexString().slice(0, 8)}` }]);
        }
        resolve({ conn, identity });
      })
      .onConnectError((_ctx, err) => { debug.error('connect', `${URI}: ${String(err)}`); reject(err); })
      .onDisconnect((_ctx, err) => {
        console.warn('[stdb] disconnected');
        debug.error('connection', `disconnected${err ? `: ${String(err)}` : ''} — reload to reconnect`);
      })
      .build();
  });
}
